#!/bin/bash

##
# port-release
#
# Description: Releases a TCP/UDP port that was being used by some process that you might know by killing that process
# Author:      Matheus Calegaro <hello@matheus.me>
# Date:        2019-01-25
##

if [ "$(whoami)" != "root" ]; then
	echo "You need root privileges to run this command effectively."
	exit 1
fi

PORT="$1"

if [ -z $PORT ]; then
  echo "No port informed! Exiting..."
  exit 1
fi

echo "Searching for process using port $PORT..."

PROC=$(netstat -putana | grep $PORT | awk '{ printf ("%s ", $7) }' | xargs)

if [ -z "$PROC" ]; then
  echo "No process using port $PORT, great!"
  exit 0
fi

for SINGLE_PROC in $PROC; do
  P=$(echo $SINGLE_PROC | cut -d '/' -f 1)

  echo "Found process '$P' using port $PORT! Killing it..."
  kill -0 $P && kill -9 $P
done

